name: easy_report
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.3
  flutter_animate: ^4.5.0
  dartz: ^0.10.1
  flutter_local_notifications: ^17.2.2
  flutter_background_service: ^5.0.7
  shared_preferences: ^2.3.2
  intl: ^0.19.0

dev_dependencies:
  freezed: ^2.5.7
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.3.10
  custom_lint:
  flutter_launcher_icons: ^0.13.1
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  source_gen: ^1.5.0

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
